{
  "formatVersion": "1.1",
  "component": {
    "group": "coder.siy",
    "module": "tansaga",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "tansaga-1.0.0.aar",
          "url": "tansaga-1.0.0.aar",
          "size": 5562,
          "sha512": "16417a719cf2da6f6d1d080691dd989ce6b30da6b185216c2fd79075c76e606f0500b4f32e4aec59b770de74024fa51c3062417bea1e0b3a4d51a6d285b97c01",
          "sha256": "fa9bce7da941b6e049f8d1d9ecfb33737bbf9414564b46a46f7454c355f3ae47",
          "sha1": "83ef3c1553561df4456d97a516b79fc76e69eeac",
          "md5": "4331d5ff67147a10248e94eb7edc6298"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "tansaga-1.0.0.aar",
          "url": "tansaga-1.0.0.aar",
          "size": 5562,
          "sha512": "16417a719cf2da6f6d1d080691dd989ce6b30da6b185216c2fd79075c76e606f0500b4f32e4aec59b770de74024fa51c3062417bea1e0b3a4d51a6d285b97c01",
          "sha256": "fa9bce7da941b6e049f8d1d9ecfb33737bbf9414564b46a46f7454c355f3ae47",
          "sha1": "83ef3c1553561df4456d97a516b79fc76e69eeac",
          "md5": "4331d5ff67147a10248e94eb7edc6298"
        }
      ]
    }
  ]
}
