{
  "formatVersion": "1.1",
  "component": {
    "group": "coder.siy",
    "module": "tansaga-local-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "tansaga-local-plugin-1.0.0.jar",
          "url": "tansaga-local-plugin-1.0.0.jar",
          "size": 157624,
          "sha512": "f1af913700414497f1399e0175d907cbc772bca296a036273048b752d0c2ec5cec4f5877e34487e122c05cea6427ba4aea5695fddc39a11210158df4f9fc1293",
          "sha256": "2bf64122a63885bb3b75784cf4e234dc6f5321b73cb364e3120ad58640e255db",
          "sha1": "ff6236da2e658199a4081caf24ef41244a19a83d",
          "md5": "58db3d0cad4c60906002c6e2bc2424aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-api",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-transform-asm",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "tansaga-local-plugin-1.0.0.jar",
          "url": "tansaga-local-plugin-1.0.0.jar",
          "size": 157624,
          "sha512": "f1af913700414497f1399e0175d907cbc772bca296a036273048b752d0c2ec5cec4f5877e34487e122c05cea6427ba4aea5695fddc39a11210158df4f9fc1293",
          "sha256": "2bf64122a63885bb3b75784cf4e234dc6f5321b73cb364e3120ad58640e255db",
          "sha1": "ff6236da2e658199a4081caf24ef41244a19a83d",
          "md5": "58db3d0cad4c60906002c6e2bc2424aa"
        }
      ]
    }
  ]
}
