{
  "formatVersion": "1.1",
  "component": {
    "group": "coder.siy",
    "module": "tansaga-local-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "tansaga-local-plugin-1.0.0.jar",
          "url": "tansaga-local-plugin-1.0.0.jar",
          "size": 157431,
          "sha512": "074c39d3456a372719bbbdfbeb4a53940a7c31e016c2bfbc61a7d15a944b5b1d9d513fdf29143f81e8f07baccb4f5eb91cfe8a3ff720738a6891e816f425a91a",
          "sha256": "09e3af1500900745a5f63321251d85f61dabec730da9c9a328a0be505f7f7853",
          "sha1": "a2b9a48c4c9cbc8dc8339cda5045a1e2d61cf8ed",
          "md5": "b33ec5d1c6a3e7b31c185ca71162e121"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-api",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-transform-asm",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "tansaga-local-plugin-1.0.0.jar",
          "url": "tansaga-local-plugin-1.0.0.jar",
          "size": 157431,
          "sha512": "074c39d3456a372719bbbdfbeb4a53940a7c31e016c2bfbc61a7d15a944b5b1d9d513fdf29143f81e8f07baccb4f5eb91cfe8a3ff720738a6891e816f425a91a",
          "sha256": "09e3af1500900745a5f63321251d85f61dabec730da9c9a328a0be505f7f7853",
          "sha1": "a2b9a48c4c9cbc8dc8339cda5045a1e2d61cf8ed",
          "md5": "b33ec5d1c6a3e7b31c185ca71162e121"
        }
      ]
    }
  ]
}
